### PR TITLE
Support for Gradle scripts in Kotlin

### PR DESCRIPTION
**Pull request by TheMrMilchmann**
Rudimentary attempt to support Gradle scripts written in Kotlin.

#### Notes

- The Kotlin version works almost exactly like the Groovy version. (The only difference is that the Kotlin script throws if the operating system cannot be detected while the Groovy version fails to resolve all dependencies.)

- `"compile"(...)` is used instead of `compile(...)` since the latter is only available if a plugin that is visible during script compilation creates a `compile` configuration.

- All addon names are wrapped in ``` ` ``` to avoid issues with names that contain characters that are invalid for identifiers. (e.g. `-` in `steamworks4j-server`)

### CODE REVIEW

**Comment by Spasi** [comment]
Thanks!

I modified the patch a bit:

- Changed `"compile"` to `compile`. The assumption is that users will paste the generated script in a proper gradle project. It is not meant to work standalone without changes.
- Now using a `compile` overload with different arguments for `groupId`, `artifactId`, etc. Looks cleaner.
- Addon artifacts were missing a closing parentheses.
- Addon names are wrapped in ``` ` ``` only if necessary.

**Comment by TheMrMilchmann** [comment]
> Changed "compile" to compile. The assumption is that users will paste the generated script in a proper gradle project. It is not meant to work standalone without changes.

The problem is that static accessors might not be available for plugins which are not applied using Gradle's [Plugins DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block).

The following script applies the java plugin in a perfectly valid way. However, this is not known during script compilation and therefore `compile` is not availalble.
```
apply {
    plugin("java")
}

repositories {
    mavenCentral();
}

dependencies {
    compile("org.lwjgl:lwjgl:3.1.6")
}
```

**Comment by Spasi** [comment]
How about something like:

```kotlin
// ...

fun DependencyHandler.lwjglModule(name: String, classifier: String? = null) =
    create("org.lwjgl", name, lwjglVersion, classifier = classifier).apply { add("compile", this) }

fun DependencyHandler.lwjglAddon(group: String, name: String, version: String) =
    create(group, name, version).apply { add("compile", this) }

dependencies {
    lwjglModule("lwjgl")
    lwjglModule("lwjgl-assimp")
    lwjglModule("lwjgl-bgfx")
    lwjglModule("lwjgl-egl")
    lwjglModule("lwjgl-glfw")
    lwjglModule("lwjgl-jawt")
    lwjglModule("lwjgl-jemalloc")
    lwjglModule("lwjgl-lmdb")
    lwjglModule("lwjgl-lz4")
    lwjglModule("lwjgl-nanovg")
    lwjglModule("lwjgl-nfd")
    lwjglModule("lwjgl-nuklear")
    lwjglModule("lwjgl-odbc")
    lwjglModule("lwjgl-openal")
    lwjglModule("lwjgl-opencl")
    lwjglModule("lwjgl-opengl")
    lwjglModule("lwjgl-opengles")
    lwjglModule("lwjgl-openvr")
    lwjglModule("lwjgl-ovr")
    lwjglModule("lwjgl-par")
    lwjglModule("lwjgl-remotery")
    lwjglModule("lwjgl-rpmalloc")
    lwjglModule("lwjgl-sse")
    lwjglModule("lwjgl-stb")
    lwjglModule("lwjgl-tinyexr")
    lwjglModule("lwjgl-tinyfd")
    lwjglModule("lwjgl-tootle")
    lwjglModule("lwjgl-vulkan")
    lwjglModule("lwjgl-xxhash")
    lwjglModule("lwjgl-yoga")
    lwjglModule("lwjgl-zstd")
    lwjglModule("lwjgl", classifier = lwjglNatives)
    lwjglModule("lwjgl-assimp", classifier = lwjglNatives)
    lwjglModule("lwjgl-bgfx", classifier = lwjglNatives)
    lwjglModule("lwjgl-glfw", classifier = lwjglNatives)
    lwjglModule("lwjgl-jemalloc", classifier = lwjglNatives)
    lwjglModule("lwjgl-lmdb", classifier = lwjglNatives)
    lwjglModule("lwjgl-lz4", classifier = lwjglNatives)
    lwjglModule("lwjgl-nanovg", classifier = lwjglNatives)
    lwjglModule("lwjgl-nfd", classifier = lwjglNatives)
    lwjglModule("lwjgl-nuklear", classifier = lwjglNatives)
    lwjglModule("lwjgl-openal", classifier = lwjglNatives)
    lwjglModule("lwjgl-opengl", classifier = lwjglNatives)
    lwjglModule("lwjgl-opengles", classifier = lwjglNatives)
    lwjglModule("lwjgl-openvr", classifier = lwjglNatives)
    lwjglModule("lwjgl-ovr", classifier = lwjglNatives)
    lwjglModule("lwjgl-par", classifier = lwjglNatives)
    lwjglModule("lwjgl-remotery", classifier = lwjglNatives)
    lwjglModule("lwjgl-rpmalloc", classifier = lwjglNatives)
    lwjglModule("lwjgl-sse", classifier = lwjglNatives)
    lwjglModule("lwjgl-stb", classifier = lwjglNatives)
    lwjglModule("lwjgl-tinyexr", classifier = lwjglNatives)
    lwjglModule("lwjgl-tinyfd", classifier = lwjglNatives)
    lwjglModule("lwjgl-tootle", classifier = lwjglNatives)
    lwjglModule("lwjgl-xxhash", classifier = lwjglNatives)
    lwjglModule("lwjgl-yoga", classifier = lwjglNatives)
    lwjglModule("lwjgl-zstd", classifier = lwjglNatives)
    lwjglAddon("org.joml", "joml", jomlVersion)
    lwjglAddon("com.code-disaster.steamworks4j", "steamworks4j", steamworks4jVersion)
    lwjglAddon("com.code-disaster.steamworks4j", "steamworks4j-server", `steamworks4j-serverVersion`)
}
```

**Comment by TheMrMilchmann** [comment]
I'm not a really a fan of this approach because it obscures the configuration to which the dependencies are added. I'd honestly just use `"compile"(...)` here to avoid making things overly complicated.

**Comment by Spasi** [comment]
You're right. Reverted to `"compile"` with f9a5696db2fe180d6071f02e11368d619c41c537.

**Pull request merged**
